### ISSUE TITLE
Licensing classification in setup.py

### ISSUE THREAD

**Issue by msalib** [Unidata/cftime#116]
This code is licensed under GPL3. That means that most commercial shops can't use it. Which is fine. Unfortunately, the setup.py classifiers list doesn't include a GPL3 tag. Which means that on PyPi, the license is listed as OSI Approved. But that doesn't tell us (or our license compliance tool) anything at all useful.

Please add a "LICENSE :: OSI APPROVED :: GNU GENERAL PUBLIC LICENSE V3 (GPLV3)" tag to your classifiers list in setup.py.

I can guarantee you that there are many people using this module who would not do so if the license was clear and obvious.

Thanks!

**Comment by jswhit** [comment]
Just looked at pyiso8601 and it looks like the license is not GPL, but is the same as specified for the rest of cftime. Since the only reason cftime needed GPL was because of the bit of pyiso8601 we use I think we can remove this.

**Comment by jswhit** [comment]
Added GPL to License classifier in setup.py in PR #127

**Comment by leifwalsh** [comment]
@jswhit are you planning to release a non-GPL version of this package? Is there a section of the code we could remove in order to remove the GPL code from this package? Is there a version of cftime already released which doesn't contain GPL-derived code?

**Comment by jswhit** [comment]
No - the GPL derived code is derived from code and is pretty essential.

**Comment by leifwalsh** [comment]
I misunderstood your previous comment, then, sorry. netCDF4 depends on this package, but does not use the GPL. Should it?

**Comment by jswhit** [comment]
None of the netCDF4 code uses cftime.  For backwards compatibility (since cftime used to be bundled with netCDF4), `from netCDF4 import date2num` imports `date2num` from cftime.  I don't know whether that's enough to require that netCDF4 use the GPL.

**Comment by leifwalsh** [comment]
Ok, thanks!

**Comment by leifwalsh** [comment]
[netCDF4 uses it here](https://github.com/Unidata/netcdf4-python/blob/master/netCDF4/_netCDF4.pyx#L6692), I don't think it's purely a compatibility convenience for end users.

**Comment by jswhit** [comment]
Good point, I missed that.  We could always ask the [calcalcs](http://meteora.ucsd.edu/~pierce/calcalcs/index.html) author if he would be willing to switch to a different license

**Comment by spencerkclark** [comment]
@jswhit the GPL nature of the license is proving to be a sticking point for us as well.  Would it be possible to reach out to the author of calcalcs to see if he would be willing to switch to a different license?

**Comment by jswhit** [comment]
I have done that and received no response, but I try again.  Here's the email I just sent:

Dear Dr. Pierce:

I am a developer of cftime, a python library for decoding time units and variable values in a netCDF file conforming to the Climate and Forecasting (CF) netCDF conventions (https:/github.com/Unidata/cftime).  Some of our code is inspired by your calcalcs.c  c program (http://meteora.ucsd.edu/~pierce/calcalcs/index.html).  I am writing to ask if you would be willing to change the license for calcalcs to LPGL or some other non-copyleft license so the other libraries that use your code or have been inspired by the algorithms in your code do not have to inherit the GPL license. 

Thanks for your consideration.

Regards, 

Jeffrey Whitaker

**Comment by spencerkclark** [comment]
I see; I appreciate you giving it another try.

**Comment by jswhit** [comment]
If we don't hear back, the only alternative would be replace the calcalcs derived code in cftime.  To do this we would need to replace two functions:

_IntJulianDayFromDate:  calculate integer julian day from date in julian, gregorian and proleptic gregorian calendars.  There are lots of implementations out there we could work from.

_IntJulianDayToDate:  compute the date (year,month,day,dayofweek,dayofyear) from the Julian day number (for the same three calendars).  This is done by advancing years from -4713,1,1 until you find a year when the julian day on Jan 1 is > the specified julian day.  Back up one year, start on Jan 1st that year and advance months calculating the julian day on the 1st of each month until you exceed the specified julian day.  Back up the the 1st of that month, and then do the same for days.

It shouldn't be hard for someone to code this without referencing the calcalcs code.  I've found lots if implementations of the first, but no alternative implementations of the second.  

The other non-real world calendars are not an issue, since I didn't use calcalcs for those.

**Comment by jswhit** [comment]
Work started (PR #226)  on reimplementing _intJulianDayFromDate and _IntJulianDayToDate from the algorithms described in the book "Calendrical Calculations" by Dershowitz and Rheingold, 3rd edition, Cambridge University Press, 2007 and the C implementation provided at https://reingold.co/calendar.C

**Comment by spencerkclark** [comment]
Awesome, thanks @jswhit; that's a big help!  If you'd like, I'd be happy to give it a review when it is ready.

**Comment by jswhit** [comment]
@spencerkclark it's ready for review now.

**Comment by jswhit** [comment]
PR #226 merged, will push out a v1.4.0 release with MIT license (and no GPL) next week.

**Comment by jswhit** [comment]
v1.4.0 is released, with no GPL
