### ISSUE TITLE
Years with more than 4 digits are not parsed

### ISSUE THREAD

**Issue by davidhassell** [Unidata/cftime#193]
Hello - years with more than 4 digits are not parsed by `_cpdef _parse_date`. This creates issues for very long climate simulations:

```
In [5]: cftime.__version__
Out[5]: '1.2.1'

In [6]: cftime.date2num(cftime.datetime(1800, 12, 1, 0, 0), 'days since 1800-1-1', '360_day')
Out[6]: 330.0

In [7]: cftime.date2num(cftime.datetime(18000, 12, 1, 0, 0), 'days since 18000-1-1', '360_day')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-06268fcf7fc7> in <module>()
----> 1 cftime.date2num(cftime.datetime(18000, 12, 1, 0, 0), 'days since 18000-1-1', '360_day')

cftime/_cftime.pyx in cftime._cftime.date2num()
cftime/_cftime.pyx in cftime._cftime._dateparse()
cftime/_cftime.pyx in cftime._cftime._parse_date()
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

```
This is easily remedied, I think, by changing `(?P<year>[+-]?[0-9]{1,4})` in [ISO8601_REGEX](https://github.com/Unidata/cftime/blob/master/cftime/_cftime.pyx#L61) to `(?P<year>[+-]?[0-9]+)`:

```
In [3]: cftime.date2num(cftime.datetime(18000, 12, 1, 0, 0), 'days since 18000-1-1', '360_day')
Out[3]: 330.0
```
All the unit tests pass when I make this change in my fork. I am happy to submit this as a PR if you agree that this is OK.

Many thanks,
David

**Comment by jswhit2** [comment]
yes, please do submit a PR

**Comment by jswhit2** [comment]
I see from the Wikipedia iso 8601 page

To represent years before 0000 or after 9999, the standard also permits the expansion of the year representation but only by prior agreement between the sender and the receiver.[20] An expanded year representation [±YYYYY] must have an agreed-upon number of extra year digits beyond the four-digit minimum, and it must be prefixed with a + or − sign[21] instead of the more common AD/BC (or CE/BCE) notation; by convention 1 BC is labelled +0000, 2 BC is labeled −0001, and so on.[22]

**Comment by jswhit** [comment]
Note that the strftime and isoformat methods assume 4 digit years

**Comment by davidhassell** [comment]
Yes - I just spotted that on #194, but they do cope with the extra digits, it turns out:
```
In [14]: "%4d" % (12345,)
Out[14]: '12345'

In [15]: d = cftime.Datetime360Day(18123, 1, 1)

In [16]: d.strftime()
Out[16]: '18123-01-01 00:00:00'

In [17]: d.isoformat()
Out[17]: '18123-01-01T00:00:00'
```

**Comment by davidhassell** [comment]
Thanks for doing the due diligence on 8601. In my PR, I'll include a change to prefix `-` or `+` the output of `isoformat` when the year is outside of the range `[0000, 9999]`. Do any other methods need this?

**Comment by jswhit** [comment]
don't think so.  Thanks for taking this on.

**Comment by jswhit** [comment]
MAXYEAR for python datetime is 9999.  Perhaps a MAXYEAR module level attribute could be added  which would determine for formatting for cftime.datetime.isoformat/cftime.datetime.strftime and how the units string is parsed?

**Comment by davidhassell** [comment]
Do you mean simply to make use of the MINYEAR/MAXYEAR attributes already imported from `datetime` in the `isoformat` and `strftime` methods, to get the best rendering given the year?

**Comment by jswhit** [comment]
No, I meant set our own MINYEAR/MAXYEAR based upon the largest year expected.  I don't think that's a good idea really, after further reflection.  

It turns out it really is only a problem in the parsing of the units string.  the `%04i` formatting used in `cftime.isoformat` does the right thing if there are more than 4 digits and just prepends zeros if there are less than 4 digits.   I think your original suggestion for modifying the regex may be sufficient.

**Comment by jswhit** [comment]
@davidhassell can you check PR #204 and see if it's sufficient to address the issue?

**Comment by davidhassell** [comment]
Thanks @jswhit. I've been away, but will now look at this.

**Comment by davidhassell** [comment]
... looks good to me. I've compiled and run the new code with no problems, and the code looks fine on paper, too.

**Comment by jswhit** [comment]
thanks @davidhassell
